### PR TITLE
GitHub: order jobs before generating configuration

### PR DESCRIPTION
**Pull request by kevmoo**
Ensures the output items are ordered correctly

### CODE REVIEW

**Comment by kevmoo** [comment]
You don't see changes here, @jakemac53 – but there is a big reordering that happens in the build repo, for instance!

**Comment by jakemac53** [comment]
I am confused about what the actual bug is here?

**Comment by kevmoo** [comment]
> I am confused about what the actual bug is here?

If you run the latest mono_repo over `build` you'll see – all of the jobs are out of order

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
> If you run the latest mono_repo over `build` you'll see – all of the jobs are out of order

Ah I see, at least the job names are weirdly out of order because they are generated inside of `_listJobs`, makes sense. I am not sure that the ordering is actually wrong in the file, but the numbers being not sequential is def weird haha.

**Pull request merged**
