### PR TITLE
drop travis

### PR DESCRIPTION
**Pull request by kevmoo**
- Drop support for travis-ci
- wip

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Comment by daniel-v** [comment]
@kevmoo why was travis support dropped?

**Comment by kevmoo** [comment]
> @kevmoo why was travis support dropped?

We stopped using travis for our stuff. It was a burden to maintain. 🤷

**Comment by daniel-v** [comment]
I suppose the following can be closed than (a little housekeeping):

https://github.com/google/mono_repo.dart/issues/145
https://github.com/google/mono_repo.dart/issues/42
https://github.com/google/mono_repo.dart/issues/244

My 2 cents: doesn't seems to have too many questions about it, seems `mono_repo` is mostly used by Dart Team or at least people who use it don't use it with Travis. I guess you [really disliked supporting travis](https://github.com/google/mono_repo.dart/pull/333/files#diff-5f9592a32eecb399fc4f8cfef0ab01c66653e7d6b37e8ed6d97e5b0eeb675ddeR20 ): 

As a community member, however, when such big changes happen, I would appreciate a removal notice. I hope I don't run into a case where I rely on something behind github.com/google or github.com/dart-lang that just gets dropped. Scary thought.

**Comment by kevmoo** [comment]
A couple of those are issue RE the migration. So I'll keep them.

FYI on support:

https://dart.dev/dart-team-packages

anything under github.com/google is NOT officially supported. Which is weird. They should call it `google-community` or something.

Things under github.com/dart-lang are (or should be) well supported.

Just an FYI!

**Pull request merged**
