### PR TITLE
Use the dart-lang provided Dart setup

### PR DESCRIPTION
**Pull request by kevmoo**
Follow-up on https://github.com/google/mono_repo.dart/pull/298

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @mit-mit

**Comment by mit-mit** [comment]
Nice! For bleeding edge / main channel , please review https://github.com/dart-lang/setup-dart/pull/16

**Comment by mit-mit** [comment]
Main channel now available in `dart-lang/setup-dart@v0.3`

**Comment by kevmoo** [comment]
Updated!

**Review by natebosch — APPROVED** [review]

**Pull request merged**
