### PR TITLE
Enable trailing commas lint

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by natebosch** [comment]
Ugh, trailing commas... you can get @jakemac53  to rubber stamp this one 😛

**Comment by jakemac53** [comment]
Do I have to? How about we trade a commitment to not change the names of any more constants :P

**Comment by kevmoo** [comment]
@jakemac53 – uh... I will try 😀

**Comment by jakemac53** [comment]
I'll take it lmao

**Review by jakemac53 — APPROVED** [review]

**Pull request merged**
